import type { Material } from '../../domain/types';
import { KRONOSPAN_BOARDS, KRONOSPAN_FLOORS } from './kronospan.generated';

/**
 * Kronospan — Kronodesign boards and Krono Original flooring.
 *
 * Kronospan manufactures in Bulgaria (Veliko Tarnovo and Burgas), so its decors
 * carry the shortest lead time of any board range on the Bulgarian market and
 * are usually the cost-effective alternative to an equivalent EGGER decor.
 *
 * Generated by `scripts/scrape-kronospan.mjs` from Kronospan's own decor pages,
 * including the colours, which are sampled from Kronospan's decor photographs.
 * Regenerate when the collection changes.
 */
export const KRONOSPAN: Material[] = [...KRONOSPAN_BOARDS, ...KRONOSPAN_FLOORS];
